version: "3.9"
services:
  server:
    image: server:latest
    ports:
      - 3001:3001
  configuration:
    image: config:latest
    ports:
      - 3002:3002
  proxy:
    image: proxy:latest
    ports:
      - 3000:3000
  shop_app:
    image: shop_app:latest
    ports:
      - 3003:3003
  orders_app:
    image: orders_app:latest
    ports:
      - 3004:3004
  cart_app:
    image: cart_app:latest
    ports:
      - 3005:3005
  auth_app:
    image: auth_app:latest
    ports:
      - 3006:3006