# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import shop_pb2 as shop__pb2


class ShopServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Shop = channel.unary_unary(
                '/shop.ShopService/Shop',
                request_serializer=shop__pb2.ShopRequest.SerializeToString,
                response_deserializer=shop__pb2.ShopResponse.FromString,
                )


class ShopServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Shop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShopServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Shop': grpc.unary_unary_rpc_method_handler(
                    servicer.Shop,
                    request_deserializer=shop__pb2.ShopRequest.FromString,
                    response_serializer=shop__pb2.ShopResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'shop.ShopService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ShopService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Shop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shop.ShopService/Shop',
            shop__pb2.ShopRequest.SerializeToString,
            shop__pb2.ShopResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
