# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from app_orders.orders_proto import orders_pb2 as orders__pb2


class OrdersServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Orders = channel.unary_unary(
                '/shop.OrdersService/Orders',
                request_serializer=orders__pb2.OrdersRequest.SerializeToString,
                response_deserializer=orders__pb2.OrdersResponse.FromString,
                )


class OrdersServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Orders(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrdersServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Orders': grpc.unary_unary_rpc_method_handler(
                    servicer.Orders,
                    request_deserializer=orders__pb2.OrdersRequest.FromString,
                    response_serializer=orders__pb2.OrdersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'shop.OrdersService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OrdersService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Orders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shop.OrdersService/Orders',
            orders__pb2.OrdersRequest.SerializeToString,
            orders__pb2.OrdersResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
