# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orders.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0corders.proto\x12\x04shop\" \n\rOrdersRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"!\n\x0eOrdersResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2F\n\rOrdersService\x12\x35\n\x06Orders\x12\x13.shop.OrdersRequest\x1a\x14.shop.OrdersResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orders_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_ORDERSREQUEST']._serialized_start=22
  _globals['_ORDERSREQUEST']._serialized_end=54
  _globals['_ORDERSRESPONSE']._serialized_start=56
  _globals['_ORDERSRESPONSE']._serialized_end=89
  _globals['_ORDERSSERVICE']._serialized_start=91
  _globals['_ORDERSSERVICE']._serialized_end=161
# @@protoc_insertion_point(module_scope)
