# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shop.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nshop.proto\x12\x04shop\"\x1e\n\x0bShopRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1f\n\x0cShopResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2>\n\x0bShopService\x12/\n\x04Shop\x12\x11.shop.ShopRequest\x1a\x12.shop.ShopResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shop_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_SHOPREQUEST']._serialized_start=20
  _globals['_SHOPREQUEST']._serialized_end=50
  _globals['_SHOPRESPONSE']._serialized_start=52
  _globals['_SHOPRESPONSE']._serialized_end=83
  _globals['_SHOPSERVICE']._serialized_start=85
  _globals['_SHOPSERVICE']._serialized_end=147
# @@protoc_insertion_point(module_scope)
